apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: felipeagger/fast-api-redis:latest
        imagePullPolicy: Always
        env:
        - name: HOST_REDIS
          value: 'redis'
        - name: PORT_REDIS
          value: '6379'
        ports:
        - containerPort: 8000
