apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: fastapi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    app: fastapi
  template:
    metadata:
      name: fastapi
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: felipeagger/fast-api-redis:latest
        env:
        - name: HOST_REDIS
          value: 'redis'
        - name: PORT_REDIS
          value: '6379'
        ports:
        - containerPort: 8000